config/routes.rb
Privlock::Application.routes.draw do
  root 'home#index'

  get '/'    => 'home#index', as: :index
  get '/:id' => 'home#show',  as: :show, id: /[0-9]+/

  get '/page/:page'              => 'home#index'
  get '/categories/:category_id' => 'home#category_writings', as: :category_writings

  get '/admin/general' => 'admin#general', as: :admin_general

  get '/admin/categories' => 'admin#categories', as: :admin_categories

  resources :writings, except: [:index, :show]

  resources :categories, only: [] do
    resources :writings, only: :index
  end

  resources :categories, except: [:new, :show, :edit] do
    patch 'up',   on: :member
    patch 'down', on: :member
  end

  resources :writings, only: [] do
    resources :comments, except: [:new, :show, :edit] do
      get 'error', on: :collection
    end
  end

  resources :settings, only: :update, path: "/admin/general"

  devise_for :users

  

end

app/models/writing.rb
# == Schema Information
#
# Table name: writings
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  content     :text             not null
#  created_at  :datetime
#  updated_at  :datetime
#  category_id :integer          not null
#  user_id     :integer          not null
#

class Writing < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :comment

  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :category_id
  validates_presence_of :user_id

  before_validation :can_not_update_user, on: :update

  before_save :is_exist_category?
  before_save :is_admin_user?, on: :create

  scope :in_categories, ->(category_ids) { where("category_id in (?)", category_ids) }

  scope :in_category_tree, ->(category_id) {
    category_ids = Category.hierarchy_categories(category_id).map(&:id)
    where("category_id in (?)", category_ids)
  }

  def last_comment_updated_at
    Comment.last_updated_at(id)
  end


  private 

  def is_exist_category?
    #return false unless self.errors.empty?
    return false if category.nil?
  end

  def is_admin_user?
    return false if user.nil?
    return false unless user.admin?
  end

  def can_not_update_user
    false if user_id_changed?
  end
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  before_action :authenticate_user!
  
  before_action :set_writing, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]



  # GET /writings/new
  def new
    @writing = Writing.new
  end

  # GET /writings/1/edit
  def edit
  end




  # POST /writings
  def create
    @writing = Writing.new(writing_params.merge(user_id: current_user.try(:id)))

    respond_to do |format|
      if current_user.try(:admin)
        if @writing.save
          format.html { redirect_to show_path(@writing), notice: 'Writing was successfully created.' }
        else
          format.html {
            set_categories
            render action: 'new'
          }
        end

      else
        format.html { redirect_to index_path, notice: 'you are not a admin.' }
      end
    end
  end

  # PATCH/PUT /writings/1
  def update
    respond_to do |format|
      if @writing.user == current_user
        if @writing.update(writing_params)
          format.html { redirect_to show_path(@writing), notice: 'Writing was successfully updated.' }
        else
          format.html {
            set_categories
            render action: 'edit'
          }
        end

      else
        format.html { redirect_to show_path(@writing), notice: 'you are not a writer.' }
      end
    end
  end

  # DELETE /writings/1
  def destroy
    if @writing.user == current_user
      @writing.destroy
      respond_to do |format|
        format.html { redirect_to root_url }
      end

    else
        format.html { redirect_to show_path(@writing), notice: 'you are not a writer.' }
    end
  end




  private

  def set_writing
    @writing = Writing.find(params[:id])
  end

  def set_categories
    @categories = Category.hierarchy_categories
  end

  def writing_params
    params.require(:writing).permit(:title, :content, :category_id)
  end
end

app/helpers/writings_helper.rb
module WritingsHelper
  def get_chained_categories(category, top_ancestor = :root, except_top = false)
    category.ancestors_and_me(top_ancestor, except_top).map { |category|
      link_to category.name, category_writings_path(category)
    }.join("/").html_safe
  end

  def get_formatted_time(datetime)
    datetime.in_time_zone('Seoul').strftime("%Y.%m.%d %H:%M:%S")
  end

  def get_formatted_date(datetime)
    datetime.in_time_zone('Seoul').strftime("%Y.%m.%d")
  end
end

app/views/writings/_admin_menu.html.erb
<% if current_user.try(:admin) %>
  <span class="admin_menu">
    <%= icon_menu_button 'edit', edit_writing_path(writing) %>
    <%= icon_menu_button 'remove', writing_path(writing), {method: :delete, data: { confirm: 'Are you sure?' }} %>
  </span>
<% end %>

app/views/writings/_comments.html.erb
<div class="comments">
  <div class="comment_list">
    <%= render comments %>
  </div>

  <%= render partial: 'comments/form', locals: {
    comment:         comment,
    writing:         writing,
    last_updated_at: comments.last ? comments.last.updated_at : nil
  } %>
</div>

app/views/writings/_form.html.erb
<%= form_for writing, html: {class: "form"} do |f| %>
  <% if writing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(writing.errors.count, "error") %> prohibited this writing from being saved:</h2>

      <ul>
      <% writing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "control-label sr-only" %>
    <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category_id, class: "control-label sr-only" %>
    <%= f.select :category_id,
                 options_from_collection_for_select(@categories, 'id', 'name', writing.category_id),
                 {include_blank: "Choose Category"},
                 {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :content, class: "control-label sr-only" %>
    <%= f.text_area :content, rows: 20, placeholder: "Content", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <button type="button" data-toggle="modal" data-target="#preview-modal" class="btn btn-info" id="open-preview-modal-button">Preview</button>
  </div>

<% end %>

app/views/writings/_header.html.erb
<div class="header jumbotron jumbotron-custom-white">
  <%= render 'shared/title' %>
</div>

app/views/writings/_writing.html.erb
<%= div_for writing do %>
  <div class="title">
    <div class="page-header">
      <h1><%= link_to writing.title, show_path(writing) %> <small><%= render partial: 'writings/admin_menu', locals: { writing: writing } %></small></h1>


      <div class="infos">
        <span class="writing_category">
          <%= get_chained_categories(writing.category) %>
        </span>

        <span class="info">
          (<span class="created_at"><%= get_formatted_time writing.created_at %></span><small>/<span class="updated_at"><%= get_formatted_time writing.updated_at %></span></small>)
        </span>
      </div>

    </div>
  </div>

  <%= javascript_tag do %>
    $(function() {
      $('#writing_<%= writing.id %> > .content').html(hmd.decode('<%= escape_javascript(writing.content).html_safe %>'));
    });
  <% end %>

  <div class="content">
    <p><strong>자바스크립트가 지원되지 않거나 자바스크립트가 활성화되지 않은 브라우저입니다.</strong></p>
    <%= writing.content %>
  </div>

  <hr/>

  <div class="infos_bottom">
    <div class="info action_menu">
      <span class="comments_count"><%= pluralize(writing.comment.count, 'comment') %></span>&nbsp;
      <%= render partial: 'writings/admin_menu', locals: { writing: writing } %>
    </div>
  </div>

  <div class="comments not_displayed">
    <hr/>
    <div class="comment_list">
    </div>

    <%= render partial: 'comments/form', locals: {
      comment: @comment,
      writing: writing,
      last_updated_timestamp: nil
    } %>
  </div>
<% end %>

app/views/writings/_writing_in_list.html.erb
<li class="writing" id="writing_<%= writing.id %>">
  <span class="info">
    <span class="created_at"><%= get_formatted_date writing.created_at %></span><small>(<span class="updated_at"><%= get_formatted_date writing.updated_at %></span>)</small>
  </span>

  <%= render partial: 'writings/admin_menu', locals: { writing: writing } %>

  <span class="writing_category">
    <%= get_chained_categories(writing.category, @category, true) %>
  </span>

  <span class="title lead">
    <%= link_to writing.title, show_path(writing) %>
  </span>

  <small>
    <span class="comments_count">
      (<%= writing.comment.count %>)
    </span>
  </small>
</li>

app/views/writings/_writing_spacer.html.erb
<div class="writing_spacer">&nbsp;</div>

app/views/writings/edit.html.erb
<%= render partial: 'form', locals: { writing: @writing } %>

app/views/writings/new.html.erb
<%= render partial: 'form', locals: { writing: @writing } %>