config/routes.rb
Privlock::Application.routes.draw do
  root 'home#index'

  get '/'    => 'home#index', as: :index
  get '/:id' => 'home#show',  as: :show, id: /[0-9]+/

  get '/page/:page'              => 'home#index'
  get '/categories/:category_id' => 'home#category_writings', as: :category_writings

  get '/admin/general' => 'admin#general', as: :admin_general

  get '/admin/categories' => 'admin#categories', as: :admin_categories

  resources :writings, except: [:index, :show]

  resources :categories, only: [] do
    resources :writings, only: :index
  end

  resources :categories, except: [:new, :show, :edit] do
    patch 'up',   on: :member
    patch 'down', on: :member
  end

  resources :writings, only: [] do
    resources :comments, except: [:new, :show, :edit] do
      get 'error', on: :collection
    end
  end

  resources :settings, only: :update, path: "/admin/general"

  devise_for :users

  

end

app/views/admin/_header.html.erb
<div class="header">
  <%= render 'shared/admin_title' %>
</div>

app/views/admin/_setting_form.html.erb
<%= form_for @setting, html: {class: "form form-horizontal"} do |f| %>
  <%= render partial: "shared/form_message", locals: {resource: @setting, resource_name: "Setting"} %>  
  <div class="form-group">
    <%= f.label :title, "Blog title", class: "control-label col-md-3" %>
    <div class="col-md-5">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :author_name, "Author Name", class: "control-label col-md-3" %>
    <div class="col-md-5">
      <%= f.text_field :author_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :author_email, "Author Email", class: "control-label col-md-3" %>
    <div class="col-md-5">
      <%= f.text_field :author_email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :number_of_writing, "# of Writings on a page", class: "control-label col-md-3" %>
    <div class="col-md-5">
      <%= f.number_field :number_of_writing, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :ccl_id, "License", class: "control-label col-md-3" %>
    <div class="col-md-5">
      <%= f.select :ccl_id,
                   options_from_collection_for_select(@licenses, 'id', 'name', @setting.ccl_id),
                   {include_blank: "Choose License"},
                   {class: "form-control", id: "ccl_select"} %>
      <% @licenses.each do |license| %>
        <div class="help-block help-block-license<%= " not_displayed" unless license.id == @setting.ccl_id %>" id="ccl_description_<%= license.id %>">
          <div>
            <%= license.description.html_safe %>
          </div>
          <div>
            <%= link_to license.url, license.url, target: '_blank' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-5 col-md-offset-3">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/_tab.html.erb
<ul class="nav nav-tabs">
  <li <%= 'class="active dead_link"'.html_safe if @tab == 'general' %>><%= link_to "General", admin_general_path %></li>
  <li <%= 'class="active dead_link"'.html_safe if @tab == "categories" %>><%= link_to "Categories", admin_categories_path %></li>
</ul>

app/views/admin/categories.html.erb
<div class="categories">
  <h3>Categories</h3>

  <table class="table table-striped">
    <% @categories.each do |category| %>
      <tr>
        <td class="col-md-2">
          <%= render category %>
        </td>

        <td class="category_edit_box col-md-6">
          <%= render partial: 'categories/form', locals: {
            category:    category,
            parents:     @parents.except_one(category.id),
            submit_text: 'Update'
          } %>
        </td>
      </tr>
    <% end %>
  </table>

</div>

<hr/>

<div class="new_category">
  <h4>New Category</h4>

  <%= render partial: 'categories/form', locals: {
    category:    @new_category,
    parents:     @parents,
  } %>
</div>

app/views/admin/general.html.erb
<h3>General Settings</h3>

<%= render partial: 'admin/setting_form' %>