config/routes.rb
Privlock::Application.routes.draw do
  root 'home#index'

  get '/'    => 'home#index', as: :index
  get '/:id' => 'home#show',  as: :show, id: /[0-9]+/

  get '/page/:page'              => 'home#index'
  get '/categories/:category_id' => 'home#category_writings', as: :category_writings

  get '/admin/general' => 'admin#general', as: :admin_general

  get '/admin/categories' => 'admin#categories', as: :admin_categories

  resources :writings, except: [:index, :show]

  resources :categories, only: [] do
    resources :writings, only: :index
  end

  resources :categories, except: [:new, :show, :edit] do
    patch 'up',   on: :member
    patch 'down', on: :member
  end

  resources :writings, only: [] do
    resources :comments, except: [:new, :show, :edit] do
      get 'error', on: :collection
    end
  end

  resources :settings, only: :update, path: "/admin/general"

  devise_for :users

  

end

app/views/shared/_admin_title.html.erb
<div class="main_title"><h1>Administration</h1></div>

app/views/shared/_author.html.erb
<% unless @setting.author_name.blank? && @setting.author_email.blank? %>
  <span class="author">
    Written by
    <% if @setting.author_name.blank? %>
      <%= link_to @setting.author_email, "mailto:#{@setting.author_email}" %>
    <% elsif @setting.author_email.blank? %>
      <%= @setting.author_name %>
    <% else %>
      <%= @setting.author_name %>(<%= link_to @setting.author_email, "mailto:#{@setting.author_email}" %>)
    <% end %>
  </span>
<% end %>

app/views/shared/_clear_floating.html.erb
<div class="clear-floating"></div>

app/views/shared/_copyright.html.erb
<% unless @setting.ccl_id.nil? %>
  <span class="copyright"><%= link_to @setting.ccl_name, @setting.ccl_url %></span>
<% end %>

app/views/shared/_form_message.html.erb
<% if resource.errors.any? %>
  <div class="alert-custom text-danger">
    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_message.html.erb
<% unless flash[:info].nil? %>
<div class="alert-custom text-info alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= flash[:info] %>
</div>
<% end %>

<% unless flash[:notice].nil? %>
<div class="alert-custom text-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= flash[:notice] %>
</div>
<% end %>

<% unless flash[:alert].nil? %>
<div class="alert-custom text-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_title.html.erb
<h1><%= link_to @setting.title, index_path %></h1>

app/views/shared/_top_menu.erb
<div class="top_menu">
  <% unless params[:controller] == "home" %>
    <% if params[:action] == "edit" %>
      <%= icon_menu_link 'arrow-left', show_path(@writing) %>
    <% end %>
    <%= icon_menu_link 'home'.html_safe, index_path %>
  <% end %>

  <% if params[:controller] == "home" %>
    <% if current_user.try(:admin) %>
      <%= icon_menu_link "plus", new_writing_path %>
      <%= icon_menu_link "cog", admin_general_path %>
    <% end %>
  <% end %>

  <div class="pull-right">
    <% if user_signed_in? %>
      <%= icon_menu_link 'log-out', destroy_user_session_path, {method: :delete} %>
      <%= icon_menu_link 'info-sign', edit_user_registration_path %>
    <% else %>
      <%= icon_menu_link 'log-in', new_user_session_path %>
    <% end %>
  </div>
</div>